import = [
    "~/.config/alacritty/themes/themes/night_owl.toml"
]

[font]
size = 16

[font.normal]
family = "CaskaydiaCove Nerd Font"

[window]
decorations = "none"
opacity = 0.85
blur = true

[window.padding]
x = 7
y = 0

[env]
TERM = "xterm-256color"

