import = [
    "~/.config/alacritty/themes/themes/night_owl.toml"
]

[font]
size = 16

[font.normal]
family = "CaskaydiaCove Nerd Font"

[window]
decorations = "none"
opacity = 0.85
blur = true

[window.padding]
x = 7
y = 0

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
	{ key = "p", mods = "Command", chars = "•`_´•p" },
	{ key = "j", mods = "Command", chars = "•`_´•j" },
	{ key = "k", mods = "Command", chars = "•`_´•k" },
	{ key = "l", mods = "Command", chars = "•`_´•l" },
	{ key = ";", mods = "Command", chars = "•`_´•;" },
]

