import = [
    "~/.config/alacritty/themes/themes/night_owl.toml"
]

[font]
size = 16

[font.normal]
family = "CaskaydiaCove NF"

[window]
decorations = "none"
opacity = 0.8
blur = true

[window.padding]
x = 7
y = 0

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
	{ key = "d", mods = "Command", chars = "•`_´•d" },
	{ key = "h", mods = "Command", chars = "•`_´•h" },
	{ key = "i", mods = "Command", chars = "•`_´•i" },
	{ key = "j", mods = "Command", chars = "•`_´•j" },
	{ key = "k", mods = "Command", chars = "•`_´•k" },
	{ key = "l", mods = "Command", chars = "•`_´•l" },
	{ key = "o", mods = "Command", chars = "•`_´•o" },
	{ key = "p", mods = "Command", chars = "•`_´•p" },
	{ key = "u", mods = "Command", chars = "•`_´•u" },
	{ key = ";", mods = "Command", chars = "•`_´•;" },
	{ key = "Key1", mods = "Control", chars = "\u001b[49;5u" },
	{ key = "Key2", mods = "Control", chars = "\u001b[50;5u" },
	{ key = "Key3", mods = "Control", chars = "\u001b[51;5u" },
	{ key = "Key4", mods = "Control", chars = "\u001b[52;5u" },
	{ key = "Key5", mods = "Control", chars = "\u001b[53;5u" },
	{ key = "Key6", mods = "Control", chars = "\u001b[54;5u" },
]

