#!/usr/bin/env bash

# Inspiration from https://github.com/FelixKratz/dotfiles/tree/e6422df2bfe674a771f5e92b478e5999e945ccf0/.config/sketchybar

source "$CONFIG_DIR/colours.sh"
source "$CONFIG_DIR/icons.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="SF Pro"

PADDINGS=3

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SHADOW=on

properties=(
	# height=29 # 38 - 9 i.e. notch height - y_offset
	corner_radius=9
	border_width=0
	margin=10
	blur_radius=50
	position=top
	padding_left=11
	padding_right=11
	color=$BAR_COLOUR
	topmost=off
	sticky=on
	font_smoothing=off
	y_offset=9
	shadow=$SHADOW
)

default=(
	drawing=on
	updates=when_shown
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOUR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOUR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  background.padding_left=$PADDINGS
  background.padding_right=$PADDINGS
  popup.background.border_width=$POPUP_BORDER_WIDTH
  popup.background.corner_radius=$POPUP_CORNER_RADIUS
  popup.background.border_color=$POPUP_BORDER_COLOUR
  popup.background.color=$POPUP_BACKGROUND_COLOUR
  popup.background.shadow.drawing=$SHADOW
)

sketchybar --bar "${properties[@]}" --default "${default[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

# sketchybar --add item clock right \
#            --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
#            --add item volume right \
#            --set volume script="$PLUGIN_DIR/volume.sh" \
#            --subscribe volume volume_change \
#            --add item battery right \
#            --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
#            --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

